// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var getTime, modal;
    modal = $('#modal');
    modal.on('hide', function() {
      return modal.find('.modal-body').html('');
    });
    $(document).on('click', '.time', function(e) {
      var html, src, target, time, youtubeid;
      e.preventDefault();
      e.stopPropagation();
      target = $(e.currentTarget);
      youtubeid = target.closest('#episode').attr('data-youtube-id');
      time = getTime(target);
      src = "http://www.youtube.com/embed/" + youtubeid + "?autoplay=1&start=" + time;
      html = "<iframe width='560' height='315' src='" + src + "' frameborder='0' allowfullscreen></iframe>";
      modal.find('.modal-body').html(html);
      return modal.modal().modal('show');
    });
    return getTime = function(target) {
      var minutes, seconds, _ref;
      _ref = target.text().split(":"), minutes = _ref[0], seconds = _ref[1];
      return parseInt(minutes) * 60 + parseInt(seconds);
    };
  });

}).call(this);
