// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return $(document).on('click', '.time', function(e) {
      e.preventDefault();
      e.stopPropagation();
      debugger;
      return $('#myModal').modal('show').show();
    });
  });

}).call(this);
